# Generated by Django 4.0.3 on 2022-03-28 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='Department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeApp.departments'),
        ),
    ]
