# Generated by Django 4.0.3 on 2022-03-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0002_alter_employees_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='emailId',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='Department',
            field=models.CharField(max_length=100),
        ),
    ]
