# Generated by Django 4.0.3 on 2022-03-28 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0003_employees_emailid_alter_employees_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='emailId',
            new_name='EmailId',
        ),
    ]
