# Generated by Django 4.0.3 on 2022-03-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0005_employees_phoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='PhoneNo',
            field=models.IntegerField(max_length=200, null=True),
        ),
    ]
